"""add bigint PK to admin_config (additive step)

Revision ID: a0b1c2d3e4f5
Revises: f9a0b1c2d3e4
Create Date: 2026-03-26

Adds new_id BIGINT IDENTITY alongside existing String(36) PK.
admin_config is a singleton table with no FK children.
"""

from alembic import op
import sqlalchemy as sa

revision = "a0b1c2d3e4f5"
down_revision = "f9a0b1c2d3e4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE admin_config "
        "ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"
    )
    op.create_unique_constraint("uq_admin_config_new_id", "admin_config", ["new_id"])


def downgrade() -> None:
    op.drop_constraint("uq_admin_config_new_id", "admin_config", type_="unique")
    op.drop_column("admin_config", "new_id")
