"""add bigint PK to candidate_profiles (additive step)

Revision ID: a4b5c6d7e8f9
Revises: f3a4b5c6d7e8
Create Date: 2026-03-26

Adds new_id BIGINT IDENTITY alongside existing UUID PK.
No FK children reference candidate_profiles.id.
"""

from alembic import op
import sqlalchemy as sa

revision = "a4b5c6d7e8f9"
down_revision = "f3a4b5c6d7e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE candidate_profiles "
        "ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"
    )
    op.create_unique_constraint("uq_candidate_profiles_new_id", "candidate_profiles", ["new_id"])


def downgrade() -> None:
    op.drop_constraint("uq_candidate_profiles_new_id", "candidate_profiles", type_="unique")
    op.drop_column("candidate_profiles", "new_id")
