"""add bigint PK to tailored_documents (additive step)

Revision ID: c0d1e2f3a4b5
Revises: b9c0d1e2f3a4
Create Date: 2026-03-26

Adds new_id BIGINT IDENTITY alongside existing UUID PK.
No FK children reference tailored_documents.id.
"""

from alembic import op
import sqlalchemy as sa

revision = "c0d1e2f3a4b5"
down_revision = "b9c0d1e2f3a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE tailored_documents "
        "ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"
    )
    op.create_unique_constraint("uq_tailored_documents_new_id", "tailored_documents", ["new_id"])


def downgrade() -> None:
    op.drop_constraint("uq_tailored_documents_new_id", "tailored_documents", type_="unique")
    op.drop_column("tailored_documents", "new_id")
