"""add bigint pk to job_descriptions (additive step)

Revision ID: c4d5e6f7a8b9
Revises: b3c4d5e6f7a8
Create Date: 2026-03-26

Additive step — adds new bigint identity columns WITHOUT touching existing PKs/FKs.
Run swap migration (d5e6f7a8b9c0) only after verifying this backfill is complete.

Changes
-------
job_descriptions:
  + new_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE
    (auto-populated for all existing rows by the identity sequence)

generation_runs:
  + new_jd_id  BIGINT NULL
    (backfilled from job_descriptions.new_id via UUID join)
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "c4d5e6f7a8b9"
down_revision: Union[str, None] = "b3c4d5e6f7a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── job_descriptions: add bigint identity column ───────────────────────
    # GENERATED BY DEFAULT AS IDENTITY auto-assigns sequential values to
    # all existing rows when the column is added.
    op.execute(
        "ALTER TABLE job_descriptions "
        "ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"
    )
    op.create_unique_constraint(
        "uq_job_descriptions_new_id", "job_descriptions", ["new_id"]
    )

    # ── generation_runs: add bigint FK column, backfill from UUID join ──────
    op.add_column(
        "generation_runs",
        sa.Column("new_jd_id", sa.BigInteger(), nullable=True),
    )
    op.execute(
        """
        UPDATE generation_runs gr
        SET new_jd_id = jd.new_id
        FROM job_descriptions jd
        WHERE gr.job_description_id = jd.id
        """
    )


def downgrade() -> None:
    op.drop_column("generation_runs", "new_jd_id")
    op.drop_constraint("uq_job_descriptions_new_id", "job_descriptions")
    op.drop_column("job_descriptions", "new_id")
