"""add bigint PK to monthly_usage (additive step)

Revision ID: c6d7e8f9a0b1
Revises: b5c6d7e8f9a0
Create Date: 2026-03-26

Adds new_id BIGINT IDENTITY alongside existing UUID PK.
No FK children reference monthly_usage.id.
"""

from alembic import op
import sqlalchemy as sa

revision = "c6d7e8f9a0b1"
down_revision = "b5c6d7e8f9a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE monthly_usage "
        "ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"
    )
    op.create_unique_constraint("uq_monthly_usage_new_id", "monthly_usage", ["new_id"])


def downgrade() -> None:
    op.drop_constraint("uq_monthly_usage_new_id", "monthly_usage", type_="unique")
    op.drop_column("monthly_usage", "new_id")
