"""add bigint PK to generation_runs (additive step)

Revision ID: e2f3a4b5c6d7
Revises: d1e2f3a4b5c6
Create Date: 2026-03-26

Adds new_id BIGINT IDENTITY to generation_runs.
Adds new_generation_run_id BIGINT to tailored_documents and evaluation_runs
and backfills via UUID join.
"""

from alembic import op
import sqlalchemy as sa

revision = "e2f3a4b5c6d7"
down_revision = "d1e2f3a4b5c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Add bigint identity column to generation_runs
    op.execute(
        "ALTER TABLE generation_runs "
        "ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"
    )
    op.create_unique_constraint("uq_generation_runs_new_id", "generation_runs", ["new_id"])

    # 2. Add new bigint FK columns to child tables
    op.add_column("tailored_documents", sa.Column("new_generation_run_id", sa.BigInteger(), nullable=True))
    op.add_column("evaluation_runs", sa.Column("new_generation_run_id", sa.BigInteger(), nullable=True))

    # 3. Backfill child FK columns via UUID join
    op.execute("""
        UPDATE tailored_documents td
        SET new_generation_run_id = gr.new_id
        FROM generation_runs gr
        WHERE td.generation_run_id = gr.id
    """)
    op.execute("""
        UPDATE evaluation_runs er
        SET new_generation_run_id = gr.new_id
        FROM generation_runs gr
        WHERE er.generation_run_id = gr.id
    """)


def downgrade() -> None:
    op.drop_column("evaluation_runs", "new_generation_run_id")
    op.drop_column("tailored_documents", "new_generation_run_id")
    op.drop_constraint("uq_generation_runs_new_id", "generation_runs", type_="unique")
    op.drop_column("generation_runs", "new_id")
