"""add bigint pk to structured_resumes (additive step)

Revision ID: e6f7a8b9c0d1
Revises: d5e6f7a8b9c0
Create Date: 2026-03-26

Additive step — adds new bigint identity column WITHOUT touching existing PK.
Run swap migration (f7a8b9c0d1e2) only after verifying this step is complete.

Changes
-------
structured_resumes:
  + new_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE
    (auto-populated for all existing rows by the identity sequence)

No FK child tables reference structured_resumes.id, so no FK columns to add.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "e6f7a8b9c0d1"
down_revision: Union[str, None] = "d5e6f7a8b9c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE structured_resumes "
        "ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"
    )
    op.create_unique_constraint(
        "uq_structured_resumes_new_id", "structured_resumes", ["new_id"]
    )


def downgrade() -> None:
    op.drop_constraint("uq_structured_resumes_new_id", "structured_resumes")
    op.drop_column("structured_resumes", "new_id")
