"""add bigint PK to billing (additive step)

Revision ID: e8f9a0b1c2d3
Revises: d7e8f9a0b1c2
Create Date: 2026-03-26

Adds new_id BIGINT IDENTITY alongside existing UUID PK.
No FK children reference billing.id.
"""

from alembic import op
import sqlalchemy as sa

revision = "e8f9a0b1c2d3"
down_revision = "d7e8f9a0b1c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE billing "
        "ADD COLUMN new_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"
    )
    op.create_unique_constraint("uq_billing_new_id", "billing", ["new_id"])


def downgrade() -> None:
    op.drop_constraint("uq_billing_new_id", "billing", type_="unique")
    op.drop_column("billing", "new_id")
